default_language_version:
  python: python3.9

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
        args:
          - "--unsafe"
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: hatch run style:lint-pyupgrade
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: hatch run style:lint-isort
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: hatch run style:lint-black
        types: [python]
        language: system
